### ISSUE TITLE
EPGStation version 1.6.5で動作しない

### ISSUE THREAD

**Issue by epgdatacapbon** [masnagam/mirakc#19]
EPGStationで新たに「/api/docs」をチェックするようになったため、動作しなくなったようです。
EPGStation側でのlogは
```
[INFO] system - wait mirakurun
[INFO] system - wait mirakurun
```
mirakcでは
```
INFO  actix_web::middleware::logger > - "GET /api/docs HTTP/1.1" 404 38 "-" "EPGStation/1.6.5 MirakurunClient/2.14.0 Node/v10.19.0 (linux)" 0.000110
DEBUG actix_web::middleware::logger > Error in response: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
となっています。

**Comment by masnagam** [comment]
0.3.0で対応してありますので，更新してみてください（#13）．

それとも，更新したけど，EPGStation 1.6.5では動作しなくなっているという報告でしょうか？

**Comment by masnagam** [comment]
ちなみに，最新版は0.4.0です．live streamingの不具合の修正が含まれています（ 7d29e5daebdcba0df0cd5ae5bf3c9986dc92cd0d ）．

**Comment by masnagam** [comment]
ソースからビルドしている場合には，ちょっとしたおまじないが必要になります．
https://github.com/masnagam/mirakc/blob/master/.github/workflows/docker.yml#L41

mirakurunからSwagger/OpenAPI jsonを抽出し，これを/api/docsから返すという対応になっています．

**Comment by epgdatacapbon** [comment]
0.4.0 を先程ソースからビルドしてました。
なるほどビルド時の対応が必要なわけですね。

**Comment by masnagam** [comment]
はい，そうなんです．
手で書いたり編集するのが面倒だったので，Mirakurunからとってきて配置することにしました．
この方法は将来変更される可能性はありますが，動かない状態を放置するのも良くなかったのでとりあえずそうしました．

抽出のための[スクリプト](https://github.com/masnagam/mirakc/blob/master/scripts/mirakurun-openapi-json)を作ってあります．これを実行するとjsonがstdoutに出力されます．

jsonファイルの配置場所はconfig.ymlで指定できるようになっています．
https://github.com/masnagam/mirakc#configuration の最後の項目です．
デフォルト値が設定してあるので，`/etc/mirakurun.openapi.json`に配置すれば，/api/docsがこれを返すようになっています．

dockerイメージには既に入れてあるので，スクリプトを使わなくても`docker cp`で抽出することも可能です．

これからドキュメントを書く予定なので，もう少しわかりやすくなると思います．

**Comment by epgdatacapbon** [comment]
いつも詳細な解説ありがとうございます。
mirakurun.openapi.jsonを配置したところ正常に動作いたしました。
