### ISSUE TITLE
/api/services で出力されるサービスの並び順

### ISSUE THREAD

**Issue by epgdatacapbon** [masnagam/mirakc#29]
以前のバージョン（0.7.0）では/api/servicesで出力されるサービスの並び順はconfig.ymlで指定されたサービスの順であったのですが、0.8.0ではチャンネル空間（GR,BS,CS）の並びも含めてバラバラになっています。

現時点のBonDriver_mirakcでは、/api/servicesの出力ではチャンネル空間がまとまっているのを前提としているため正しく動作しなくなってしまいました。
BonDriver_mirakcの修正（内部でソート）も可能なのですが、そうするとユーザーがチャンネルの順番を変えられないことになります。

そこで、0.7.0と同じように、/api/services（/api/channels）でのサービス（チャンネル）の出力をconfig.ymlに記載の順番に戻していただくことはできませんでしょうか。

**Comment by masnagam** [comment]
修正することにします．少々お待ち下さい．

**Comment by masnagam** [comment]
確認があります．あるチャンネルに複数のサービスがある場合，このサービスの順番に何か仮定していることはありますか？
例えば，sidで昇順になっていることを仮定しているとか？

以前は並びはPATでのサービスの順番になっていたと思いますが，場合によってはこれはランダムになってしまうかもしれません．

**Comment by epgdatacapbon** [comment]
並び順はユーザーが設定できるように、config.ymlの指定の順番になるのが理想です。例えば私のconfig.ymlだと
```
  - name: MX1
    type: GR
    channel: '16'
    services: [23608]
  - name: MX2
    type: GR
    channel: '16'
    services: [23610]
```
としており、MX1,MX2の順番で/api/servicesに表示されるのが理想です。

**Comment by epgdatacapbon** [comment]
余談ですが、その場合でも、現在のBonDriver_mirakcだとユーザーがconfig.xmlで意図的にGR,BS,GR,CSのような順番でチャンネルを記述すると正常に動作しません。
これに対処する場合はBonDriver_mirakcを修正すべきだと思っています。

**Comment by masnagam** [comment]
質問の意図がうまく伝わらなかったようなので，具体的な例で質問します．

以下のような設定をしていた場合

```yaml
- name: ETV
  type: GR
  channel: '26'
- name: NHK
  type: GR
  channel: '27'
```

`/api/services'は常に

- ＮＨＫＥテレ１東京
- ＮＨＫＥテレ２東京
- ＮＨＫＥテレ３東京
- ＮＨＫ総合１・東京
- ＮＨＫ総合２・東京

**とはならず**，

- ＮＨＫＥテレ３東京
- ＮＨＫＥテレ１東京
- ＮＨＫＥテレ２東京
- ＮＨＫ総合２・東京
- ＮＨＫ総合１・東京

のように，同じチャンネルのサービスの順番はランダムとなってしまう可能性がありますが，これは大丈夫でしょうか？
これはサービスをハッシュマップで管理するように変更したため，値のイテレーションで順番が保証されないためです（挿入順序が保証されるハッシュマップもありますが，それは使っていません）．

https://github.com/masnagam/mirakc/issues/29#issuecomment-633926762 に例として書いていただいたような，１つのサービスを１つのチャンネルとして登録している場合は，上記のようなこと発生しません．

なお，ETVとNHKの順番が変わってしまう以下のようなことは起きないように修正します．

- ＮＨＫ総合１・東京
- ＮＨＫ総合２・東京
- ＮＨＫＥテレ１東京
- ＮＨＫＥテレ２東京
- ＮＨＫＥテレ３東京

**Comment by epgdatacapbon** [comment]
詳細なご説明ありがとうございます。同じチャンネルのサービスの順番がランダムであってもBondDriver_mirakcは動作すると思われますが、やはりsidが昇順の方がユーザーにとって便利かと思います。
お手数おかけ致しますがよろしくお願い致します。

**Comment by masnagam** [comment]
そうですよね．．以前はvectorだったので順番通りでしたが．
ちょっと考えてみます．

**Comment by epgdatacapbon** [comment]
ありがとうございます。
javaで言うところのLinkedHashMapでいける気がしましたが、メモリとかスレッドセーフ的な問題ですかね。

**Comment by masnagam** [comment]
毎回フルスキャンに成功して古いハッシュマップを新しいハッシュマップに置き換えるだけなら簡単で良いですが，サービススキャン時に放送休止状態になっているチャンネルなどがあると，そのチャンネルに関するサービスは更新できないため，古い情報と新しい情報をマージしたりする必要があります．そういうイレギュラーな場合でも順番がおかしくなることがないようにする必要があります．

自分でハッシュマップを実装する場合は何も問題ありませんが，既存のライブラリを使う場合には，削除や挿入済みアイテム更新時に順番がどうなるのかなど，いくつか確認が必要な項目があります．

**Comment by epgdatacapbon** [comment]
なるほど。たしかに。
チャンネルスキャンはプログラム設定時（初回）に行うだけのものが多い中、mirakcははるかに高頻度ですから複雑ですね。

**Comment by masnagam** [comment]
Docker Hubのmasterイメージのビルドには25分程度かかるので，明日以降暇なときに動作確認してみてください．ユニットテストレベルでは順序が保たれていることを確認済みです．

問題修正の確認が取れたら，タグを付けようと思います．

**Comment by epgdatacapbon** [comment]
動作を確認いたしました。いつもながらの素早いご対応ありがとうございました。

**Comment by epgdatacapbon** [comment]
mirakcを起動してチェンネルスキャンが終了すると、config.ymlで指定されたサービスの順で
services.jsonが作成され、その順番で/api/servicesも表示されますが、すでにservices.jsonが
作成されている状態でmirakcを再起動すると、チャンネルスキャンの最中であっても
/api/servicesでサービス名を取得できるものの、本来の（config.ymlに記載の）順番通りでは
なくなってしまいます。なお、スキャンが完了すると、本来の順番になります。

仕様のようですが一応報告まで。

**Comment by masnagam** [comment]
報告ありがとうございます．

確かにそうなるみたいですね．
一部の処理で誤って`HashMap`が使われていることが原因のようです．
直しておきます．
